run1.1:
	@qemu-system-i386 -hda hd.img -serial null -parallel stdio
run1.2:
	@qemu-system-i386 -hda num.img -serial null -parallel stdio
run2.1:
	@qemu-system-i386 -hda inter.img -serial null -parallel stdio
run2.2:
	@qemu-system-i386 -hda num2.img -serial null -parallel stdio 
run2.3:
	@qemu-system-i386 -hda myos.img -serial null -parallel stdio
